const statsData = [
  {
    "id":"str01",
    "name": "Fuerza",
    "abbreviation":"Str",
    "score": "1",
    "Probabilidad de Golpe": -5,
    "Ajuste de Daño": -4,
    "Peso Autorizado": 0.5,
    "Esfuerzo Máximo": 1.5,
    "Abrir Puertas": "1",
    "Doblar Barras/Alzar Puertas": 0
  },
  {
    "id":"str02",
    "name": "Fuerza",
    "abbreviation":"Str",
    "score": "2",
    "Probabilidad de Golpe": -3,
    "Ajuste de Daño": -2,
    "Peso Autorizado": 0.5,
    "Esfuerzo Máximo": 2.5,
    "Abrir Puertas": "1",
    "Doblar Barras/Alzar Puertas": 0
  },
  {
    "id":"str03",
    "name": "Fuerza",
    "abbreviation":"Str",
    "score": "3",
    "Probabilidad de Golpe": -3,
    "Ajuste de Daño": -1,
    "Peso Autorizado": 2.5,
    "Esfuerzo Máximo": 5,
    "Abrir Puertas": "2",
    "Doblar Barras/Alzar Puertas": 0
  },
  {
    "id":"str04",
    "name": "Fuerza",
    "abbreviation":"Str",
    "score": "4-5",
    "Probabilidad de Golpe": -2,
    "Ajuste de Daño": -1,
    "Peso Autorizado": 5,
    "Esfuerzo Máximo": 23,
    "Abrir Puertas": "3",
    "Doblar Barras/Alzar Puertas": 0
  },
  {
    "id":"str05",
    "name": "Fuerza",
    "abbreviation":"Str",
    "score": "6-7",
    "Probabilidad de Golpe": -1,
    "Ajuste de Daño": 0,
    "Peso Autorizado": 10,
    "Esfuerzo Máximo": 28,
    "Abrir Puertas": "4",
    "Doblar Barras/Alzar Puertas": 0
  },
  {
    "id":"str06",
    "name": "Fuerza",
    "abbreviation":"Str",
    "score": "8-9",
    "Probabilidad de Golpe": 0,
    "Ajuste de Daño": 0,
    "Peso Autorizado": 18,
    "Esfuerzo Máximo": 45,
    "Abrir Puertas": "5",
    "Doblar Barras/Alzar Puertas": 0.01
  },
  {
    "id":"str07",
    "name": "Fuerza",
    "abbreviation":"Str",
    "score": "10-11",
    "Probabilidad de Golpe": 0,
    "Ajuste de Daño": 0,
    "Peso Autorizado": 20,
    "Esfuerzo Máximo": 58,
    "Abrir Puertas": "6",
    "Doblar Barras/Alzar Puertas": 0.02
  },
  {
    "id":"str08",
    "name": "Fuerza",
    "abbreviation":"Str",
    "score": "12-13",
    "Probabilidad de Golpe": 0,
    "Ajuste de Daño": 0,
    "Peso Autorizado": 23,
    "Esfuerzo Máximo": 70,
    "Abrir Puertas": "7",
    "Doblar Barras/Alzar Puertas": 0.04
  },
  {
    "id":"str09",
    "name": "Fuerza",
    "abbreviation":"Str",
    "score": "14-15",
    "Probabilidad de Golpe": 0,
    "Ajuste de Daño": 0,
    "Peso Autorizado": 28,
    "Esfuerzo Máximo": 85,
    "Abrir Puertas": "8",
    "Doblar Barras/Alzar Puertas": 0.07
  },
  {
    "id":"str10",
    "name": "Fuerza",
    "abbreviation":"Str",
    "score": "16",
    "Probabilidad de Golpe": 0,
    "Ajuste de Daño": 1,
    "Peso Autorizado": 35,
    "Esfuerzo Máximo": 98,
    "Abrir Puertas": "9",
    "Doblar Barras/Alzar Puertas": 0.1
  },
  {
    "id":"str11",
    "name": "Fuerza",
    "abbreviation":"Str",
    "score": "17",
    "Probabilidad de Golpe": 1,
    "Ajuste de Daño": 1,
    "Peso Autorizado": 43,
    "Esfuerzo Máximo": 110,
    "Abrir Puertas": "10",
    "Doblar Barras/Alzar Puertas": 0.13
  },
  {
    "id":"str12",
    "name": "Fuerza",
    "abbreviation":"Str",
    "score": "18",
    "Probabilidad de Golpe": 1,
    "Ajuste de Daño": 2,
    "Peso Autorizado": 55,
    "Esfuerzo Máximo": 130,
    "Abrir Puertas": "11",
    "Doblar Barras/Alzar Puertas": 0.16
  },
  {
    "id":"str13",
    "name": "Fuerza",
    "abbreviation":"Str",
    "score": "18/01-50",
    "Probabilidad de Golpe": 1,
    "Ajuste de Daño": 3,
    "Peso Autorizado": 70,
    "Esfuerzo Máximo": 140,
    "Abrir Puertas": "12",
    "Doblar Barras/Alzar Puertas": 0.2
  },
  {
    "id":"str14",
    "name": "Fuerza",
    "abbreviation":"Str",
    "score": "18/51-75",
    "Probabilidad de Golpe": 2,
    "Ajuste de Daño": 3,
    "Peso Autorizado": 80,
    "Esfuerzo Máximo": 155,
    "Abrir Puertas": "13",
    "Doblar Barras/Alzar Puertas": 0.25
  },
  {
    "id":"str15",
    "name": "Fuerza",
    "abbreviation":"Str",
    "score": "18/76-90",
    "Probabilidad de Golpe": 2,
    "Ajuste de Daño": 4,
    "Peso Autorizado": 95,
    "Esfuerzo Máximo": 165,
    "Abrir Puertas": "14",
    "Doblar Barras/Alzar Puertas": 0.3
  },
  {
    "id":"str16",
    "name": "Fuerza",
    "abbreviation":"Str",
    "score": "18/91-99",
    "Probabilidad de Golpe": 2,
    "Ajuste de Daño": 5,
    "Peso Autorizado": 120,
    "Esfuerzo Máximo": 190,
    "Abrir Puertas": "15(3)",
    "Doblar Barras/Alzar Puertas": 0.35
  },
  {
    "id":"str17",
    "name": "Fuerza",
    "abbreviation":"Str",
    "score": "18/00",
    "Probabilidad de Golpe": 3,
    "Ajuste de Daño": 6,
    "Peso Autorizado": 170,
    "Esfuerzo Máximo": 240,
    "Abrir Puertas": "16(6)",
    "Doblar Barras/Alzar Puertas": 0.4
  },
  {
    "id":"str18",
    "name": "Fuerza",
    "abbreviation":"Str",
    "score": "19",
    "Probabilidad de Golpe": 3,
    "Ajuste de Daño": 7,
    "Peso Autorizado": 245,
    "Esfuerzo Máximo": 320,
    "Abrir Puertas": "16(8)",
    "Doblar Barras/Alzar Puertas": 0.5
  },
  {
    "id":"str19",
    "name": "Fuerza",
    "abbreviation":"Str",
    "score": "20",
    "Probabilidad de Golpe": 3,
    "Ajuste de Daño": 8,
    "Peso Autorizado": 270,
    "Esfuerzo Máximo": 350,
    "Abrir Puertas": "17(10)",
    "Doblar Barras/Alzar Puertas": 0.6
  },
  {
    "id":"str20",
    "name": "Fuerza",
    "abbreviation":"Str",
    "score": "21",
    "Probabilidad de Golpe": 4,
    "Ajuste de Daño": 9,
    "Peso Autorizado": 320,
    "Esfuerzo Máximo": 405,
    "Abrir Puertas": "17(12)",
    "Doblar Barras/Alzar Puertas": 0.7
  },
  {
    "id":"str21",
    "name": "Fuerza",
    "abbreviation":"Str",
    "score": "22",
    "Probabilidad de Golpe": 4,
    "Ajuste de Daño": 10,
    "Peso Autorizado": 395,
    "Esfuerzo Máximo": 485,
    "Abrir Puertas": "18(14)",
    "Doblar Barras/Alzar Puertas": 0.8
  },
  {
    "id":"str22",
    "name": "Fuerza",
    "abbreviation":"Str",
    "score": "23",
    "Probabilidad de Golpe": 5,
    "Ajuste de Daño": 11,
    "Peso Autorizado": 2470,
    "Esfuerzo Máximo": 565,
    "Abrir Puertas": "18(16)",
    "Doblar Barras/Alzar Puertas": 0.9
  },
  {
    "id":"str23",
    "name": "Fuerza",
    "abbreviation":"Str",
    "score": "24",
    "Probabilidad de Golpe": 6,
    "Ajuste de Daño": 12,
    "Peso Autorizado": 620,
    "Esfuerzo Máximo": 720,
    "Abrir Puertas": "19(17)",
    "Doblar Barras/Alzar Puertas": 0.95
  },
  {
    "id":"str24",
    "name": "Fuerza",
    "abbreviation":"Str",
    "score": "25",
    "Probabilidad de Golpe": 7,
    "Ajuste de Daño": 14,
    "Peso Autorizado": 770,
    "Esfuerzo Máximo": 875,
    "Abrir Puertas": "19(18)",
    "Doblar Barras/Alzar Puertas": 0.99
  },
  {
    "id":"dex01",
    "name": "Destreza",
    "abbreviation":"Dex",
    "score": "1",
    "Ajuste Reacción": -6,
    "Ajuste Ataque Proyectil": -6,
    "Ajuste Defensivo": 5
  },
  {
    "id":"dex02",
    "name": "Destreza",
    "abbreviation":"Dex",
    "score": "2",
    "Ajuste Reacción": -4,
    "Ajuste Ataque Proyectil": -4,
    "Ajuste Defensivo": 5
  },
  {
    "id":"dex03",
    "name": "Destreza",
    "abbreviation":"Dex",
    "score": "3",
    "Ajuste Reacción": -3,
    "Ajuste Ataque Proyectil": -3,
    "Ajuste Defensivo": 4
  },
  {
    "id":"dex04",
    "name": "Destreza",
    "abbreviation":"Dex",
    "score": "4",
    "Ajuste Reacción": -2,
    "Ajuste Ataque Proyectil": -2,
    "Ajuste Defensivo": 3
  },
  {
    "id":"dex05",
    "name": "Destreza",
    "abbreviation":"Dex",
    "score": "5",
    "Ajuste Reacción": -1,
    "Ajuste Ataque Proyectil": -1,
    "Ajuste Defensivo": 2
  },
  {
    "id":"dex06",
    "name": "Destreza",
    "abbreviation":"Dex",
    "score": "6",
    "Ajuste Reacción": 0,
    "Ajuste Ataque Proyectil": 0,
    "Ajuste Defensivo": 1
  },
  {
    "id":"dex07",
    "name": "Destreza",
    "abbreviation":"Dex",
    "score": "7-14",
    "Ajuste Reacción": 0,
    "Ajuste Ataque Proyectil": 0,
    "Ajuste Defensivo": 0
  },
  {
    "id":"dex08",
    "name": "Destreza",
    "abbreviation":"Dex",
    "score": "15",
    "Ajuste Reacción": 0,
    "Ajuste Ataque Proyectil": 0,
    "Ajuste Defensivo": -1
  },
  {
    "id":"dex09",
    "name": "Destreza",
    "abbreviation":"Dex",
    "score": "16",
    "Ajuste Reacción": 1,
    "Ajuste Ataque Proyectil": 1,
    "Ajuste Defensivo": -2
  },
  {
    "id":"dex10",
    "name": "Destreza",
    "abbreviation":"Dex",
    "score": "17",
    "Ajuste Reacción": 2,
    "Ajuste Ataque Proyectil": 2,
    "Ajuste Defensivo": -3
  },
  {
    "id":"dex11",
    "name": "Destreza",
    "abbreviation":"Dex",
    "score": "18",
    "Ajuste Reacción": 2,
    "Ajuste Ataque Proyectil": 2,
    "Ajuste Defensivo": -4
  },
  {
    "id":"dex12",
    "name": "Destreza",
    "abbreviation":"Dex",
    "score": "19",
    "Ajuste Reacción": 3,
    "Ajuste Ataque Proyectil": 3,
    "Ajuste Defensivo": -4
  },
  {
    "id":"dex13",
    "name": "Destreza",
    "abbreviation":"Dex",
    "score": "20",
    "Ajuste Reacción": 3,
    "Ajuste Ataque Proyectil": 3,
    "Ajuste Defensivo": -4
  },
  {
    "id":"dex14",
    "name": "Destreza",
    "abbreviation":"Dex",
    "score": "21-23",
    "Ajuste Reacción": 4,
    "Ajuste Ataque Proyectil": 4,
    "Ajuste Defensivo": -5
  },
  {
    "id":"dex15",
    "name": "Destreza",
    "abbreviation":"Dex",
    "score": "24-25",
    "Ajuste Reacción": 5,
    "Ajuste Ataque Proyectil": 5,
    "Ajuste Defensivo": -6
  },
  {
    "id": "con01",
    "name": "Constitución",
    "abbreviation": "Con",
    "score": "1",
    "Ajuste Punto de Golpe": "-3",
    "Shock del Sistema": "25%",
    "Supervivencia a la Revivificación": "30%",
    "Protección Contra Veneno": -2,
    "Regeneración": "Nada"
  },
  {
    "id": "con02",
    "name": "Constitución",
    "abbreviation": "Con",
    "score": "2",
    "Ajuste Punto de Golpe": "-2",
    "Shock del Sistema": "30%",
    "Supervivencia a la Revivificación": "35%",
    "Protección Contra Veneno": -1,
    "Regeneración": "Nada"
  },
  {
    "id": "con03",
    "name": "Constitución",
    "abbreviation": "Con",
    "score": "3",
    "Ajuste Punto de Golpe": "-2",
    "Shock del Sistema": "35%",
    "Supervivencia a la Revivificación": "40%",
    "Protección Contra Veneno": 0,
    "Regeneración": "Nada"
  },
  {
    "id": "con04",
    "name": "Constitución",
    "abbreviation": "Con",
    "score": "4",
    "Ajuste Punto de Golpe": "-1",
    "Shock del Sistema": "40%",
    "Supervivencia a la Revivificación": "45%",
    "Protección Contra Veneno": 0,
    "Regeneración": "Nada"
  },
  {
    "id": "con05",
    "name": "Constitución",
    "abbreviation": "Con",
    "score": "5",
    "Ajuste Punto de Golpe": "-1",
    "Shock del Sistema": "45%",
    "Supervivencia a la Revivificación": "50%",
    "Protección Contra Veneno": 0,
    "Regeneración": "Nada"
  },
  {
    "id": "con06",
    "name": "Constitución",
    "abbreviation": "Con",
    "score": "6",
    "Ajuste Punto de Golpe": "-1",
    "Shock del Sistema": "50%",
    "Supervivencia a la Revivificación": "55%",
    "Protección Contra Veneno": 0,
    "Regeneración": "Nada"
  },
  {
    "id": "con07",
    "name": "Constitución",
    "abbreviation": "Con",
    "score": "7",
    "Ajuste Punto de Golpe": "0",
    "Shock del Sistema": "55%",
    "Supervivencia a la Revivificación": "60%",
    "Protección Contra Veneno": 0,
    "Regeneración": "Nada"
  },
  {
    "id": "con08",
    "name": "Constitución",
    "abbreviation": "Con",
    "score": "8",
    "Ajuste Punto de Golpe": "0",
    "Shock del Sistema": "60%",
    "Supervivencia a la Revivificación": "65%",
    "Protección Contra Veneno": 0,
    "Regeneración": "Nada"
  },
  {
    "id": "con09",
    "name": "Constitución",
    "abbreviation": "Con",
    "score": "9",
    "Ajuste Punto de Golpe": "0",
    "Shock del Sistema": "65%",
    "Supervivencia a la Revivificación": "70%",
    "Protección Contra Veneno": 0,
    "Regeneración": "Nada"
  },
  {
    "id": "con10",
    "name": "Constitución",
    "abbreviation": "Con",
    "score": "10",
    "Ajuste Punto de Golpe": "0",
    "Shock del Sistema": "70%",
    "Supervivencia a la Revivificación": "75%",
    "Protección Contra Veneno": 0,
    "Regeneración": "Nada"
  },
  {
    "id": "con11",
    "name": "Constitución",
    "abbreviation": "Con",
    "score": "11",
    "Ajuste Punto de Golpe": "0",
    "Shock del Sistema": "75%",
    "Supervivencia a la Revivificación": "80%",
    "Protección Contra Veneno": 0,
    "Regeneración": "Nada"
  },
  {
    "id": "con12",
    "name": "Constitución",
    "abbreviation": "Con",
    "score": "12",
    "Ajuste Punto de Golpe": "0",
    "Shock del Sistema": "80%",
    "Supervivencia a la Revivificación": "85%",
    "Protección Contra Veneno": 0,
    "Regeneración": "Nada"
  },
  {
    "id": "con13",
    "name": "Constitución",
    "abbreviation": "Con",
    "score": "13",
    "Ajuste Punto de Golpe": "0",
    "Shock del Sistema": "85%",
    "Supervivencia a la Revivificación": "90%",
    "Protección Contra Veneno": 0,
    "Regeneración": "Nada"
  },
  {
    "id": "con14",
    "name": "Constitución",
    "abbreviation": "Con",
    "score": "14",
    "Ajuste Punto de Golpe": "0",
    "Shock del Sistema": "88%",
    "Supervivencia a la Revivificación": "92%",
    "Protección Contra Veneno": 0,
    "Regeneración": "Nada"
  },
  {
    "id": "con15",
    "name": "Constitución",
    "abbreviation": "Con",
    "score": "15",
    "Ajuste Punto de Golpe": "+1",
    "Shock del Sistema": "90%",
    "Supervivencia a la Revivificación": "94%",
    "Protección Contra Veneno": 0,
    "Regeneración": "Nada"
  },
  {
    "id": "con16",
    "name": "Constitución",
    "abbreviation": "Con",
    "score": "16",
    "Ajuste Punto de Golpe": "+2",
    "Shock del Sistema": "95%",
    "Supervivencia a la Revivificación": "96%",
    "Protección Contra Veneno": 0,
    "Regeneración": "Nada"
  },
  {
    "id": "con17",
    "name": "Constitución",
    "abbreviation": "Con",
    "score": "17",
    "Ajuste Punto de Golpe": "2(+3)*",
    "Shock del Sistema": "97%",
    "Supervivencia a la Revivificación": "98%",
    "Protección Contra Veneno": 0,
    "Regeneración": "Nada"
  },
  {
    "id": "con18",
    "name": "Constitución",
    "abbreviation": "Con",
    "score": "18",
    "Ajuste Punto de Golpe": "2(+4)*",
    "Shock del Sistema": "99%",
    "Supervivencia a la Revivificación": "100%",
    "Protección Contra Veneno": 0,
    "Regeneración": "Nada"
  },
  {
    "id": "con19",
    "name": "Constitución",
    "abbreviation": "Con",
    "score": "19",
    "Ajuste Punto de Golpe": "2(+5)*",
    "Shock del Sistema": "99%",
    "Supervivencia a la Revivificación": "100%",
    "Protección Contra Veneno": 1,
    "Regeneración": "Nada"
  },
  {
    "id": "con20",
    "name": "Constitución",
    "abbreviation": "Con",
    "score": "20",
    "Ajuste Punto de Golpe": "2(+5)**",
    "Shock del Sistema": "99%",
    "Supervivencia a la Revivificación": "100%",
    "Protección Contra Veneno": 1,
    "Regeneración": "1/6 turnos"
  },
  {
    "id": "con21",
    "name": "Constitución",
    "abbreviation": "Con",
    "score": "21",
    "Ajuste Punto de Golpe": "2(+6)***",
    "Shock del Sistema": "99%",
    "Supervivencia a la Revivificación": "100%",
    "Protección Contra Veneno": 2,
    "Regeneración": "1/5 turnos"
  },
  {
    "id": "con22",
    "name": "Constitución",
    "abbreviation": "Con",
    "score": "22",
    "Ajuste Punto de Golpe": "2(+6)***",
    "Shock del Sistema": "99%",
    "Supervivencia a la Revivificación": "100%",
    "Protección Contra Veneno": 2,
    "Regeneración": "1/4 turnos"
  },
  {
    "id": "con23",
    "name": "Constitución",
    "abbreviation": "Con",
    "score": "23",
    "Ajuste Punto de Golpe": "2(+6)****",
    "Shock del Sistema": "99%",
    "Supervivencia a la Revivificación": "100%",
    "Protección Contra Veneno": 3,
    "Regeneración": "1/3 turnos"
  },
  {
    "id": "con24",
    "name": "Constitución",
    "abbreviation": "Con",
    "score": "24",
    "Ajuste Punto de Golpe": "2(+7)****",
    "Shock del Sistema": "99%",
    "Supervivencia a la Revivificación": "100%",
    "Protección Contra Veneno": 3,
    "Regeneración": "1/2 turnos"
  },
  {
    "id": "con25",
    "name": "Constitución",
    "abbreviation": "Con",
    "score": "24",
    "Ajuste Punto de Golpe": "2(+7)****",
    "Shock del Sistema": "100%",
    "Supervivencia a la Revivificación": "100%",
    "Protección Contra Veneno": 4,
    "Regeneración": "1/1 turnos"
  },
  {
    "id": "int01",
    "name": "Inteligencia",
    "abbreviation": "Int",
    "score": "1",
    "Número de Lenguajes": 0,
    "Nivel de Conjuros Aprendidos": 0,
    "Oportunidad de Conjuros": "0",
    "Número Máximo de Conjuros": "0",
    "Inmunidad a Conjuros":"0",
  },
  {
    "id": "int02",
    "name": "Inteligencia",
    "abbreviation": "Int",
    "score": "2-8",
    "Número de Lenguajes": 1,
    "Nivel de Conjuros Aprendidos": 0,
    "Oportunidad de Conjuros": "0",
    "Número Máximo de Conjuros": "0",
    "Inmunidad a Conjuros":"0",
  },
  {
    "id": "int03",
    "name": "Inteligencia",
    "abbreviation": "Int",
    "score": "9",
    "Número de Lenguajes": 2,
    "Nivel de Conjuros Aprendidos": 4,
    "Oportunidad de Conjuros": "35%",
    "Número Máximo de Conjuros": "6",
    "Inmunidad a Conjuros":"0",
  },
  {
    "id": "int04",
    "name": "Inteligencia",
    "abbreviation": "Int",
    "score": "10",
    "Número de Lenguajes": 2,
    "Nivel de Conjuros Aprendidos": 5,
    "Oportunidad de Conjuros": "40%",
    "Número Máximo de Conjuros": "7",
    "Inmunidad a Conjuros":"0",
  },
  {
    "id": "int05",
    "name": "Inteligencia",
    "abbreviation": "Int",
    "score": "11",
    "Número de Lenguajes": 2,
    "Nivel de Conjuros Aprendidos": 5,
    "Oportunidad de Conjuros": "45%",
    "Número Máximo de Conjuros": "7",
    "Inmunidad a Conjuros":"0",
  },
  {
    "id": "int06",
    "name": "Inteligencia",
    "abbreviation": "Int",
    "score": "12",
    "Número de Lenguajes": 3,
    "Nivel de Conjuros Aprendidos": 6,
    "Oportunidad de Conjuros": "50%",
    "Número Máximo de Conjuros": "7",
    "Inmunidad a Conjuros":"0",
  },
  {
    "id": "int07",
    "name": "Inteligencia",
    "abbreviation": "Int",
    "score": "13",
    "Número de Lenguajes": 3,
    "Nivel de Conjuros Aprendidos": 6,
    "Oportunidad de Conjuros": "55%",
    "Número Máximo de Conjuros": "9",
    "Inmunidad a Conjuros":"0",
  },
  {
    "id": "int08",
    "name": "Inteligencia",
    "abbreviation": "Int",
    "score": "14",
    "Número de Lenguajes": 4,
    "Nivel de Conjuros Aprendidos": 7,
    "Oportunidad de Conjuros": "60%",
    "Número Máximo de Conjuros": "9",
    "Inmunidad a Conjuros":"0",
  },
  {
    "id": "int09",
    "name": "Inteligencia",
    "abbreviation": "Int",
    "score": "15",
    "Número de Lenguajes": 4,
    "Nivel de Conjuros Aprendidos": 7,
    "Oportunidad de Conjuros": "65%",
    "Número Máximo de Conjuros": "11",
    "Inmunidad a Conjuros":"0",
  },
  {
    "id": "int10",
    "name": "Inteligencia",
    "abbreviation": "Int",
    "score": "16",
    "Número de Lenguajes": 5,
    "Nivel de Conjuros Aprendidos": 8,
    "Oportunidad de Conjuros": "70%",
    "Número Máximo de Conjuros": "11",
    "Inmunidad a Conjuros":"0",
  },
  {
    "id": "int11",
    "name": "Inteligencia",
    "abbreviation": "Int",
    "score": "17",
    "Número de Lenguajes": 6,
    "Nivel de Conjuros Aprendidos": 8,
    "Oportunidad de Conjuros": "75%",
    "Número Máximo de Conjuros": "14",
    "Inmunidad a Conjuros":"0",
  },
  {
    "id": "int11",
    "name": "Inteligencia",
    "abbreviation": "Int",
    "score": "18",
    "Número de Lenguajes": 7,
    "Nivel de Conjuros Aprendidos": 9,
    "Oportunidad de Conjuros": "85%",
    "Número Máximo de Conjuros": "18",
    "Inmunidad a Conjuros":"0",
  },
  {
    "id": "int12",
    "name": "Inteligencia",
    "abbreviation": "Int",
    "score": "19",
    "Número de Lenguajes": 8,
    "Nivel de Conjuros Aprendidos": 9,
    "Oportunidad de Conjuros": "95%",
    "Número Máximo de Conjuros": "Todos",
    "Inmunidad a Conjuros":"Ilusiones nivel 1",
  },
  {
    "id": "int13",
    "name": "Inteligencia",
    "abbreviation": "Int",
    "score": "20",
    "Número de Lenguajes": 9,
    "Nivel de Conjuros Aprendidos": 9,
    "Oportunidad de Conjuros": "96%",
    "Número Máximo de Conjuros": "Todos",
    "Inmunidad a Conjuros":"Ilusiones nivel 2",
  },
  {
    "id": "int14",
    "name": "Inteligencia",
    "abbreviation": "Int",
    "score": "21",
    "Número de Lenguajes": 10,
    "Nivel de Conjuros Aprendidos": 9,
    "Oportunidad de Conjuros": "97%",
    "Número Máximo de Conjuros": "Todos",
    "Inmunidad a Conjuros":"Ilusiones nivel 3",
  },
  {
    "id": "int15",
    "name": "Inteligencia",
    "abbreviation": "Int",
    "score": "22",
    "Número de Lenguajes": 11,
    "Nivel de Conjuros Aprendidos": 9,
    "Oportunidad de Conjuros": "98%",
    "Número Máximo de Conjuros": "Todos",
    "Inmunidad a Conjuros":"Ilusiones nivel 4",
  },
  {
    "id": "int16",
    "name": "Inteligencia",
    "abbreviation": "Int",
    "score": "23",
    "Número de Lenguajes": 12,
    "Nivel de Conjuros Aprendidos": 9,
    "Oportunidad de Conjuros": "99%",
    "Número Máximo de Conjuros": "Todos",
    "Inmunidad a Conjuros":"Ilusiones nivel 5",
  },
  {
    "id": "int17",
    "name": "Inteligencia",
    "abbreviation": "Int",
    "score": "24",
    "Número de Lenguajes": 15,
    "Nivel de Conjuros Aprendidos": 9,
    "Oportunidad de Conjuros": "100%",
    "Número Máximo de Conjuros": "Todos",
    "Inmunidad a Conjuros":"Ilusiones nivel 6",
  },
  {
    "id": "int18",
    "name": "Inteligencia",
    "abbreviation": "Int",
    "score": "25",
    "Número de Lenguajes": 20,
    "Nivel de Conjuros Aprendidos": 9,
    "Oportunidad de Conjuros": "100%",
    "Número Máximo de Conjuros": "Todos",
    "Inmunidad a Conjuros":"Ilusiones nivel 7",
  },
  {
    "id": "wis01",
    "name": "Sabiduría",
    "abbreviation": "Wis",
    "score": "1",
    "Ajuste Defensa Mágica": "-6",
    "Bonificación Conjuros": "0",
    "Posibilidad Fracaso de Conjuros": "80%",
    "Inmunidad a los Conjuros": "No"
  },
  {
    "id": "wis02",
    "name": "Sabiduría",
    "abbreviation": "Wis",
    "score": "2",
    "Ajuste Defensa Mágica": "-4",
    "Bonificación Conjuros": "0",
    "Posibilidad Fracaso de Conjuros": "60%",
    "Inmunidad a los Conjuros": "No"
  },
  {
    "id": "wis03",
    "name": "Sabiduría",
    "abbreviation": "Wis",
    "score": "3",
    "Ajuste Defensa Mágica": "-3",
    "Bonificación Conjuros": "0",
    "Posibilidad Fracaso de Conjuros": "50%",
    "Inmunidad a los Conjuros": "No"
  },
  {
    "id": "wis04",
    "name": "Sabiduría",
    "abbreviation": "Wis",
    "score": "4",
    "Ajuste Defensa Mágica": "-2",
    "Bonificación Conjuros": "0",
    "Posibilidad Fracaso de Conjuros": "45%",
    "Inmunidad a los Conjuros": "No"
  },
  {
    "id": "wis05",
    "name": "Sabiduría",
    "abbreviation": "Wis",
    "score": "5",
    "Ajuste Defensa Mágica": "-1",
    "Bonificación Conjuros": "0",
    "Posibilidad Fracaso de Conjuros": "40%",
    "Inmunidad a los Conjuros": "No"
  },
  {
    "id": "wis06",
    "name": "Sabiduría",
    "abbreviation": "Wis",
    "score": "6",
    "Ajuste Defensa Mágica": "-1",
    "Bonificación Conjuros": "0",
    "Posibilidad Fracaso de Conjuros": "35%",
    "Inmunidad a los Conjuros": "No"
  },
  {
    "id": "wis07",
    "name": "Sabiduría",
    "abbreviation": "Wis",
    "score": "7",
    "Ajuste Defensa Mágica": "-1",
    "Bonificación Conjuros": "0",
    "Posibilidad Fracaso de Conjuros": "30%",
    "Inmunidad a los Conjuros": "No"
  },
  {
    "id": "wis08",
    "name": "Sabiduría",
    "abbreviation": "Wis",
    "score": "8",
    "Ajuste Defensa Mágica": "0",
    "Bonificación Conjuros": "0",
    "Posibilidad Fracaso de Conjuros": "25%",
    "Inmunidad a los Conjuros": "No"
  },
  {
    "id": "wis09",
    "name": "Sabiduría",
    "abbreviation": "Wis",
    "score": "9",
    "Ajuste Defensa Mágica": "0",
    "Bonificación Conjuros": "0",
    "Posibilidad Fracaso de Conjuros": "20%",
    "Inmunidad a los Conjuros": "No"
  },
  {
    "id": "wis10",
    "name": "Sabiduría",
    "abbreviation": "Wis",
    "score": "10",
    "Ajuste Defensa Mágica": "0",
    "Bonificación Conjuros": "0",
    "Posibilidad Fracaso de Conjuros": "15%",
    "Inmunidad a los Conjuros": "No"
  },
  {
    "id": "wis11",
    "name": "Sabiduría",
    "abbreviation": "Wis",
    "score": "11",
    "Ajuste Defensa Mágica": "0",
    "Bonificación Conjuros": "0",
    "Posibilidad Fracaso de Conjuros": "10%",
    "Inmunidad a los Conjuros": "No"
  },
  {
    "id": "wis12",
    "name": "Sabiduría",
    "abbreviation": "Wis",
    "score": "12",
    "Ajuste Defensa Mágica": "0",
    "Bonificación Conjuros": "0",
    "Posibilidad Fracaso de Conjuros": "5%",
    "Inmunidad a los Conjuros": "No"
  },
  {
    "id": "wis13",
    "name": "Sabiduría",
    "abbreviation": "Wis",
    "score": "13-14",
    "Ajuste Defensa Mágica": "0",
    "Bonificación Conjuros": "1",
    "Posibilidad Fracaso de Conjuros": "0%",
    "Inmunidad a los Conjuros": "No"
  },
  {
    "id": "wis14",
    "name": "Sabiduría",
    "abbreviation": "Wis",
    "score": "15",
    "Ajuste Defensa Mágica": "+1",
    "Bonificación Conjuros": "2",
    "Posibilidad Fracaso de Conjuros": "0%",
    "Inmunidad a los Conjuros": "No"
  },
  {
    "id": "wis15",
    "name": "Sabiduría",
    "abbreviation": "Wis",
    "score": "16",
    "Ajuste Defensa Mágica": "+2",
    "Bonificación Conjuros": "2",
    "Posibilidad Fracaso de Conjuros": "0%",
    "Inmunidad a los Conjuros": "No"
  },
  {
    "id": "wis16",
    "name": "Sabiduría",
    "abbreviation": "Wis",
    "score": "17",
    "Ajuste Defensa Mágica": "+3",
    "Bonificación Conjuros": "3",
    "Posibilidad Fracaso de Conjuros": "0%",
    "Inmunidad a los Conjuros": "No"
  },
  {
    "id": "wis17",
    "name": "Sabiduría",
    "abbreviation": "Wis",
    "score": "18",
    "Ajuste Defensa Mágica": "+4",
    "Bonificación Conjuros": "4",
    "Posibilidad Fracaso de Conjuros": "0%",
    "Inmunidad a los Conjuros": "No"
  },
  {
    "id": "wis18",
    "name": "Sabiduría",
    "abbreviation": "Wis",
    "score": "19",
    "Ajuste Defensa Mágica": "+4",
    "Bonificación Conjuros": "1, 4",
    "Posibilidad Fracaso de Conjuros": "0%",
    "Inmunidad a los Conjuros": "Cause Fear, Charm Person, Command, Friedns, Hypnotism"
  },
  {
    "id": "wis19",
    "name": "Sabiduría",
    "abbreviation": "Wis",
    "score": "20",
    "Ajuste Defensa Mágica": "+4",
    "Bonificación Conjuros": "2, 4",
    "Posibilidad Fracaso de Conjuros": "0%",
    "Inmunidad a los Conjuros": "Forget, Hold Person, Ray of Enfeeblement, Scare"
  },
  {
    "id": "wis20",
    "name": "Sabiduría",
    "abbreviation": "Wis",
    "score": "21",
    "Ajuste Defensa Mágica": "+4",
    "Bonificación Conjuros": "3, 5",
    "Posibilidad Fracaso de Conjuros": "0%",
    "Inmunidad a los Conjuros": "Fear"
  },
  {
    "id": "wis21",
    "name": "Sabiduría",
    "abbreviation": "Wis",
    "score": "22",
    "Ajuste Defensa Mágica": "+4",
    "Bonificación Conjuros": "4, 5",
    "Posibilidad Fracaso de Conjuros": "0%",
    "Inmunidad a los Conjuros": "Charm Monster, Confusion, Emotion, Fumble, Suggestion"
  },
  {
    "id": "wis22",
    "name": "Sabiduría",
    "abbreviation": "Wis",
    "score": "23",
    "Ajuste Defensa Mágica": "+4",
    "Bonificación Conjuros": "1, 6",
    "Posibilidad Fracaso de Conjuros": "0%",
    "Inmunidad a los Conjuros": "Chaos, Feeblemind, Hold Monster, Magic Jar, Quest"
  },
  {
    "id": "wis23",
    "name": "Sabiduría",
    "abbreviation": "Wis",
    "score": "24",
    "Ajuste Defensa Mágica": "+4",
    "Bonificación Conjuros": "5, 6",
    "Posibilidad Fracaso de Conjuros": "0%",
    "Inmunidad a los Conjuros": "Geas, Mass Suggestion, Rod of Rulership"
  },
  {
    "id": "wis24",
    "name": "Sabiduría",
    "abbreviation": "Wis",
    "score": "25",
    "Ajuste Defensa Mágica": "+4",
    "Bonificación Conjuros": "6, 7",
    "Posibilidad Fracaso de Conjuros": "0%",
    "Inmunidad a los Conjuros": "Antipathy/Sympathy, Death Spell, Mass Charm"
  },
  {
    "id": "cha01",
    "name": "Carisma",
    "abbreviation": "Cha",
    "score": "1",
    "Número de Servidores": 0,
    "Lealtad Base": "-8",
    "Ajuste de Reacción": "-7"
  },
  {
    "id": "cha02",
    "name": "Carisma",
    "abbreviation": "Cha",
    "score": "2",
    "Número de Servidores": 1,
    "Lealtad Base": "-7",
    "Ajuste de Reacción": "-6"
  },
  {
    "id": "cha03",
    "name": "Carisma",
    "abbreviation": "Cha",
    "score": "3",
    "Número de Servidores": 1,
    "Lealtad Base": "-6",
    "Ajuste de Reacción": "-5"
  },
  {
    "id": "cha04",
    "name": "Carisma",
    "abbreviation": "Cha",
    "score": "4",
    "Número de Servidores": 1,
    "Lealtad Base": "-5",
    "Ajuste de Reacción": "-4"
  },
  {
    "id": "cha05",
    "name": "Carisma",
    "abbreviation": "Cha",
    "score": "5",
    "Número de Servidores": 2,
    "Lealtad Base": "-4",
    "Ajuste de Reacción": "-3"
  },
  {
    "id": "cha06",
    "name": "Carisma",
    "abbreviation": "Cha",
    "score": "6",
    "Número de Servidores": 2,
    "Lealtad Base": "-3",
    "Ajuste de Reacción": "-2"
  },
  {
    "id": "cha07",
    "name": "Carisma",
    "abbreviation": "Cha",
    "score": "7",
    "Número de Servidores": 3,
    "Lealtad Base": "-2",
    "Ajuste de Reacción": "-1"
  },
  {
    "id": "cha08",
    "name": "Carisma",
    "abbreviation": "Cha",
    "score": "8",
    "Número de Servidores": 3,
    "Lealtad Base": "-1",
    "Ajuste de Reacción": "0"
  },
  {
    "id": "cha09",
    "name": "Carisma",
    "abbreviation": "Cha",
    "score": "9-11",
    "Número de Servidores": 4,
    "Lealtad Base": "0",
    "Ajuste de Reacción": "0"
  },
  {
    "id": "cha10",
    "name": "Carisma",
    "abbreviation": "Cha",
    "score": "12",
    "Número de Servidores": 5,
    "Lealtad Base": "0",
    "Ajuste de Reacción": "0"
  },
  {
    "id": "cha11",
    "name": "Carisma",
    "abbreviation": "Cha",
    "score": "13",
    "Número de Servidores": 5,
    "Lealtad Base": "0",
    "Ajuste de Reacción": "+1"
  },
  {
    "id": "cha12",
    "name": "Carisma",
    "abbreviation": "Cha",
    "score": "14",
    "Número de Servidores": 6,
    "Lealtad Base": "+1",
    "Ajuste de Reacción": "+2"
  },
  {
    "id": "cha13",
    "name": "Carisma",
    "abbreviation": "Cha",
    "score": "15",
    "Número de Servidores": 7,
    "Lealtad Base": "+3",
    "Ajuste de Reacción": "+3"
  },
  {
    "id": "cha14",
    "name": "Carisma",
    "abbreviation": "Cha",
    "score": "16",
    "Número de Servidores": 8,
    "Lealtad Base": "+4",
    "Ajuste de Reacción": "+5"
  },
  {
    "id": "cha15",
    "name": "Carisma",
    "abbreviation": "Cha",
    "score": "17",
    "Número de Servidores": 10,
    "Lealtad Base": "+6",
    "Ajuste de Reacción": "+6"
  },
  {
    "id": "cha16",
    "name": "Carisma",
    "abbreviation": "Cha",
    "score": "18",
    "Número de Servidores": 15,
    "Lealtad Base": "+8",
    "Ajuste de Reacción": "+7"
  },
  {
    "id": "cha17",
    "name": "Carisma",
    "abbreviation": "Cha",
    "score": "19",
    "Número de Servidores": 20,
    "Lealtad Base": "+10",
    "Ajuste de Reacción": "+8"
  },
  {
    "id": "cha18",
    "name": "Carisma",
    "abbreviation": "Cha",
    "score": "20",
    "Número de Servidores": 25,
    "Lealtad Base": "+12",
    "Ajuste de Reacción": "+9"
  },
  {
    "id": "cha19",
    "name": "Carisma",
    "abbreviation": "Cha",
    "score": "21",
    "Número de Servidores": 30,
    "Lealtad Base": "+14",
    "Ajuste de Reacción": "+10"
  },
  {
    "id": "cha20",
    "name": "Carisma",
    "abbreviation": "Cha",
    "score": "22",
    "Número de Servidores": 35,
    "Lealtad Base": "+16",
    "Ajuste de Reacción": "+11"
  },
  {
    "id": "cha21",
    "name": "Carisma",
    "abbreviation": "Cha",
    "score": "23",
    "Número de Servidores": 40,
    "Lealtad Base": "+18",
    "Ajuste de Reacción": "+12"
  },
  {
    "id": "cha22",
    "name": "Carisma",
    "abbreviation": "Cha",
    "score": "24",
    "Número de Servidores": 45,
    "Lealtad Base": "+20",
    "Ajuste de Reacción": "+13"
  },
  {
    "id": "cha23",
    "name": "Carisma",
    "abbreviation": "Cha",
    "score": "25",
    "Número de Servidores": 50,
    "Lealtad Base": "+20",
    "Ajuste de Reacción": "+14"
  }
]